services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        sync: false
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: false
      - key: DATABASE_SSL_REJECT_UNAUTHORIZED
        value: false
      - key: DATABASE_SHEMA
        value: public
      - key: DATABASE_POOL_MIN
        value: 1
      - key: DATABASE_POOL_MAX
        value: 4
      - key: JWT_SECRET
        generateValue: true